import { useEffect, useState } from 'react';
import { ArrowUpRight, CircleDollarSign, CreditCard, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api } from '../api/axios';
import { ErrorState } from '../components/ui';
import type { Cliente, Operacion, Pagina } from '../types';
import { getErrorMessage } from '../utils/errors';
import { formatCurrency, toDateInput } from '../utils/format';
export default function AdminDashboardView() { const [clientes, setClientes] = useState<Cliente[] | null>(null); const [pagosMes, setPagosMes] = useState<number | null>(null); const [error, setError] = useState(''); useEffect(() => { api.get<Cliente[]>('/api/clientes').then(({ data }) => setClientes(data)).catch((err) => setError(getErrorMessage(err, 'No pudimos cargar el resumen.'))); const hoy = new Date(); api.get<Pagina<Operacion>>('/api/auditoria', { params: { desde: toDateInput(new Date(hoy.getFullYear(), hoy.getMonth(), 1)), hasta: toDateInput(hoy), accion: 'Pago', pagina: 1, tamanoPagina: 1 } }).then(({ data }) => setPagosMes(data.totalRegistros)).catch(() => setPagosMes(null)); }, []); const cartera = clientes?.reduce((s, c) => s + c.deudaActual, 0) ?? 0; const activos = clientes?.filter((c) => c.estado === 'Activo').length ?? 0; const hora = new Date().getHours(); const saludo = hora < 12 ? 'Buenos días' : hora < 19 ? 'Buenas tardes' : 'Buenas noches'; return <div><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-widest text-indigo-600">Resumen general</p><h1 className="mt-2 text-3xl font-black">{saludo}, administrador</h1><p className="mt-2 text-slate-500">Esto es lo que pasa con tu cartera.</p></div><Link to="clientes" className="rounded-xl bg-indigo-600 px-4 py-3 text-sm font-semibold text-white">Ver clientes <ArrowUpRight className="inline h-4 w-4" /></Link></div>{error && <div className="mb-6"><ErrorState message={error} /></div>}<div className="grid gap-4 sm:grid-cols-3"><Metric icon={<CircleDollarSign />} label="Cartera por cobrar (capital)" value={clientes ? formatCurrency(cartera) : '...'} /><Metric icon={<Users />} label="Clientes activos" value={clientes ? String(activos) : '...'} /><Metric icon={<CreditCard />} label="Pagos registrados este mes" value={pagosMes === null ? '...' : String(pagosMes)} /></div>{clientes && clientes.length === 0 && <div className="mt-8 rounded-2xl border border-dashed bg-white p-10 text-center"><CircleDollarSign className="mx-auto h-10 w-10 text-indigo-600" /><h2 className="mt-4 text-lg font-bold">Tu cartera empieza aquí</h2><p className="mt-2 text-sm text-slate-500">Registra tu primer cliente y empieza a construir crédito.</p></div>}</div>; }
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-5 text-indigo-600">{icon}</div><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-black tabular-nums">{value}</p></div>; }
