import { FormEvent, useEffect, useState } from 'react';
import { CircleCheck } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import { api } from '../api/axios';
import { Button, Input } from '../components/ui';
import type { RegisterAdminRequest, RegistroResponse } from '../types';
import { getErrorMessage } from '../utils/errors';
export default function RegisterView() { const navigate = useNavigate(); const [form, setForm] = useState<RegisterAdminRequest>({ ruc: '', razonSocial: '', giro: '', usuario: '', password: '' }); const [loading, setLoading] = useState(false); const [done, setDone] = useState(''); useEffect(() => { if (!done) return; const timer = setTimeout(() => navigate('/login?rol=Admin'), 2000); return () => clearTimeout(timer); }, [done, navigate]); const update = (key: keyof RegisterAdminRequest) => (e: React.ChangeEvent<HTMLInputElement>) => setForm({ ...form, [key]: key === 'ruc' ? e.target.value.replace(/\D/g, '').slice(0, 11) : e.target.value }); const submit = async (e: FormEvent) => { e.preventDefault(); setLoading(true); try { const { data } = await api.post<RegistroResponse>('/api/auth/register/admin', { ...form, razonSocial: form.razonSocial.trim(), giro: form.giro.trim(), usuario: form.usuario.trim() }); const message = data?.mensaje || 'Tienda registrada correctamente.'; setDone(message); toast.success(message); } catch (err) { toast.error(getErrorMessage(err, 'No pudimos registrar la tienda.')); } finally { setLoading(false); } }; return <div className="min-h-screen bg-slate-50 px-5 py-10"><div className="mx-auto max-w-xl"><Link to="/login" className="text-xl font-black">finvex<span className="text-indigo-600">.</span></Link><div className="mt-10 rounded-2xl border bg-white p-7 shadow-sm sm:p-10"><p className="text-sm font-bold uppercase tracking-widest text-indigo-600">Comienza con orden</p><h1 className="mt-2 text-3xl font-black">Registra tu negocio</h1><p className="mt-2 text-slate-500">Crea tu espacio para vender a crédito.</p>{done ? <div className="mt-8 rounded-2xl bg-emerald-50 p-6 text-emerald-800"><CircleCheck className="mb-3 h-8 w-8" /><p className="font-bold">{done}</p><p className="mt-1 text-sm">Te llevamos al inicio de sesión...</p><Link to="/login?rol=Admin" className="mt-4 inline-block text-sm font-bold text-indigo-600">Ir ahora</Link></div> : <form onSubmit={submit} className="mt-8 grid gap-5 sm:grid-cols-2"><Input label="RUC" help="Registro Único de Contribuyentes: 11 dígitos." value={form.ruc} onChange={update('ruc')} inputMode="numeric" pattern="\d{11}" title="El RUC debe tener 11 dígitos" required /><Input label="Razón social" value={form.razonSocial} onChange={update('razonSocial')} required /><Input label="Giro del negocio" help="Actividad principal de la tienda, por ejemplo: venta de abarrotes." value={form.giro} onChange={update('giro')} required /><Input label="Usuario administrador" value={form.usuario} onChange={update('usuario')} autoComplete="username" required /><Input label="Contraseña" help="Mínimo 6 caracteres." type="password" value={form.password} onChange={update('password')} autoComplete="new-password" required minLength={6} /><Button loading={loading} type="submit" className="sm:col-span-2">Crear mi cuenta</Button></form>}</div></div></div>; }
