import { useState } from 'react';
import { ChevronDown, ChevronRight } from 'lucide-react';
import { EstadoBadge, HelpTip } from './ui';
import type { Compra, Cuota, Moneda } from '../types';
import { formatCurrency, formatDate, parseDate, toDateInput } from '../utils/format';
import { HELP } from '../utils/help';
export const estadoCompra = (c: Compra): string => (c.estado === 'Mora' || c.interesMoratorio > 0 ? 'Mora' : c.estado);
const vencida = (cuota: Cuota) => cuota.estado !== 'Pagada' && toDateInput(parseDate(cuota.vencimiento)) < toDateInput();
export function CuotasTable({ cuotas, moneda }: { cuotas: Cuota[]; moneda?: Moneda }) { return <div className="table-scroll overflow-x-auto" tabIndex={0} aria-label="Cronograma de cuotas, desplaza horizontalmente en pantallas pequeñas"><table className="w-full min-w-[680px] text-left text-sm"><thead className="text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-3 py-2">N.º</th><th className="px-3 py-2">Vencimiento</th><th className="px-3 py-2 text-right">Cuota</th><th className="px-3 py-2 text-right">Interés</th><th className="px-3 py-2 text-right">Amortización</th><th className="px-3 py-2">Estado</th></tr></thead><tbody className="divide-y divide-slate-200">{cuotas.map((c) => <tr key={c.numero} className={c.estado === 'Mora' || vencida(c) ? 'bg-rose-50/60' : ''}><td className="px-3 py-2.5 font-semibold">{c.numero}</td><td className="whitespace-nowrap px-3 py-2.5">{formatDate(c.vencimiento)}</td><td className="px-3 py-2.5 text-right font-bold tabular-nums">{formatCurrency(c.cuota, moneda)}</td><td className="px-3 py-2.5 text-right tabular-nums">{formatCurrency(c.interes, moneda)}</td><td className="px-3 py-2.5 text-right tabular-nums">{formatCurrency(c.amortizacion, moneda)}</td><td className="px-3 py-2.5"><EstadoBadge estado={c.estado === 'Pendiente' && vencida(c) ? 'Mora' : c.estado} /></td></tr>)}</tbody></table></div>; }
export function ComprasList({ compras, moneda }: { compras: Compra[]; moneda?: Moneda }) { const [expanded, setExpanded] = useState<number | null>(null); return <div className="divide-y">{compras.map((item) => { const hasCuotas = !!item.cuotas?.length; const open = expanded === item.compraId; return <div key={item.compraId}><button type="button" aria-expanded={hasCuotas ? open : undefined} onClick={() => hasCuotas && setExpanded(open ? null : item.compraId)} className={`flex min-h-11 w-full flex-wrap items-start gap-3 p-3 text-left focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-inset focus-visible:ring-indigo-200 sm:flex-nowrap sm:items-center sm:p-5 ${hasCuotas ? 'hover:bg-slate-50' : 'cursor-default'}`}>{hasCuotas ? open ? <ChevronDown className="mt-0.5 h-5 w-5 shrink-0 text-slate-400" /> : <ChevronRight className="mt-0.5 h-5 w-5 shrink-0 text-slate-400" /> : <span className="w-5 shrink-0" />}<div className="min-w-0 flex-1"><p className="break-words font-bold">{item.producto}</p><p className="mt-1 flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-500"><span>Capital {formatCurrency(item.capitalPendiente, moneda)}</span><span className="inline-flex items-center gap-1">Interés {formatCurrency(item.interesCompensatorio, moneda)}<HelpTip text={HELP.interesCompensatorio} /></span><span className={`inline-flex items-center gap-1 ${item.interesMoratorio > 0 ? 'font-semibold text-rose-600' : ''}`}>Mora {formatCurrency(item.interesMoratorio, moneda)}<HelpTip text={HELP.interesMoratorio} /></span>{hasCuotas && <span>{item.cuotas!.length} cuota(s) pendiente(s)</span>}</p></div><div className="ml-8 w-full text-left sm:ml-0 sm:w-auto sm:text-right"><b className="tabular-nums">{formatCurrency(item.totalExigible, moneda)}</b><div className="mt-1"><EstadoBadge estado={estadoCompra(item)} /></div></div></button>{open && item.cuotas && <div className="border-t bg-slate-50 px-2 py-3 sm:px-5 sm:pl-12"><CuotasTable cuotas={item.cuotas} moneda={moneda} /></div>}</div>; })}</div>; }
