import type { ButtonHTMLAttributes, InputHTMLAttributes, ReactNode, SelectHTMLAttributes } from 'react';
import { CircleAlert, Inbox, Info, LoaderCircle, RotateCw } from 'lucide-react';
export function Button({ children, loading, variant = 'primary', className = '', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { loading?: boolean; variant?: 'primary' | 'secondary' | 'ghost' | 'danger' }) { const variants = { primary: 'bg-indigo-600 text-white hover:bg-indigo-700', secondary: 'bg-white text-slate-700 border border-slate-200 hover:bg-slate-50', ghost: 'text-slate-500 hover:bg-slate-100', danger: 'bg-rose-50 text-rose-700 hover:bg-rose-100' }; return <button className={`inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold transition disabled:cursor-not-allowed disabled:opacity-60 ${variants[variant]} ${className}`} disabled={loading || props.disabled} {...props}>{loading && <LoaderCircle className="h-4 w-4 animate-spin" />}{children}</button>; }
export function HelpTip({ text }: { text: string }) { return <span tabIndex={0} role="note" aria-label={text} className="group relative inline-flex cursor-help align-middle text-slate-400 outline-none hover:text-indigo-600 focus:text-indigo-600" onClick={(e) => e.preventDefault()}><Info className="h-3.5 w-3.5" /><span className="pointer-events-none absolute left-1/2 top-full z-50 mt-2 hidden w-64 -translate-x-1/2 rounded-xl bg-slate-900 px-3 py-2 text-xs font-normal leading-5 text-white shadow-xl group-hover:block group-focus:block">{text}</span></span>; }
function FieldLabel({ label, help }: { label?: string; help?: string }) { if (!label) return null; return <span className="flex items-center gap-1.5">{label}{help && <HelpTip text={help} />}</span>; }
export function Input({ label, help, ...props }: InputHTMLAttributes<HTMLInputElement> & { label?: string; help?: string }) { return <label className="block space-y-1.5 text-sm font-medium text-slate-700"><FieldLabel label={label} help={help} /><input className="w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm outline-none transition placeholder:text-slate-400 focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100 disabled:bg-slate-50 disabled:text-slate-500" {...props} /></label>; }
export function Select({ label, help, children, ...props }: SelectHTMLAttributes<HTMLSelectElement> & { label?: string; help?: string }) { return <label className="block space-y-1.5 text-sm font-medium text-slate-700"><FieldLabel label={label} help={help} /><select className="w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm outline-none transition focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100 disabled:bg-slate-50" {...props}>{children}</select></label>; }
export function Checkbox({ label, help, ...props }: InputHTMLAttributes<HTMLInputElement> & { label: string; help?: string }) { return <label className="flex items-center gap-2.5 text-sm font-medium text-slate-700"><input type="checkbox" className="h-4 w-4 rounded border-slate-300 accent-indigo-600" {...props} /><FieldLabel label={label} help={help} /></label>; }
export function Modal({ open, title, onClose, children, wide }: { open: boolean; title: string; onClose: () => void; children: ReactNode; wide?: boolean }) { if (!open) return null; return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4 backdrop-blur-sm"><div className={`max-h-[90vh] w-full ${wide ? 'max-w-3xl' : 'max-w-xl'} overflow-auto rounded-2xl bg-white p-6 shadow-2xl`}><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-bold text-slate-900">{title}</h2><button aria-label="Cerrar" onClick={onClose} className="rounded-lg px-2 text-2xl text-slate-400 hover:bg-slate-100">×</button></div>{children}</div></div>; }
export function ConfirmModal({ open, title, message, confirmLabel = 'Confirmar', danger, loading, onConfirm, onClose }: { open: boolean; title: string; message: ReactNode; confirmLabel?: string; danger?: boolean; loading?: boolean; onConfirm: () => void; onClose: () => void }) { return <Modal open={open} title={title} onClose={onClose}><div className="text-sm leading-6 text-slate-600">{message}</div><div className="mt-6 flex justify-end gap-3"><Button variant="secondary" onClick={onClose} disabled={loading}>Cancelar</Button><Button variant={danger ? 'danger' : 'primary'} loading={loading} onClick={onConfirm}>{confirmLabel}</Button></div></Modal>; }
const tones = { success: 'bg-emerald-50 text-emerald-700 ring-emerald-200', danger: 'bg-rose-50 text-rose-700 ring-rose-200', warning: 'bg-amber-50 text-amber-700 ring-amber-200', info: 'bg-indigo-50 text-indigo-700 ring-indigo-200', neutral: 'bg-slate-100 text-slate-600 ring-slate-200' };
export type Tone = keyof typeof tones;
export function Badge({ tone = 'neutral', children }: { tone?: Tone; children: ReactNode }) { return <span className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-semibold ring-1 ring-inset ${tones[tone]}`}>{children}</span>; }
const estadoTones: Record<string, [Tone, string]> = { Pagada: ['success', 'Pagada'], Pendiente: ['info', 'Al día'], Mora: ['danger', 'En mora'], Activo: ['success', 'Activo'], Activa: ['success', 'Activa'], Inactivo: ['neutral', 'Inactivo'], Inactiva: ['neutral', 'Inactiva'] };
export function EstadoBadge({ estado }: { estado: string }) { const [tone, label] = estadoTones[estado] ?? ['neutral', estado]; return <Badge tone={tone}>{label}</Badge>; }
export function PageHeader({ eyebrow, title, subtitle, actions }: { eyebrow: string; title: string; subtitle?: ReactNode; actions?: ReactNode }) { return <div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end print:mb-4"><div><p className="text-sm font-bold uppercase tracking-widest text-indigo-600">{eyebrow}</p><h1 className="mt-2 text-3xl font-black">{title}</h1>{subtitle && <div className="mt-2 text-slate-500">{subtitle}</div>}</div>{actions && <div className="flex flex-wrap gap-3 print:hidden">{actions}</div>}</div>; }
export function Loading({ text = 'Cargando...' }: { text?: string }) { return <div className="grid min-h-60 place-items-center text-sm text-slate-500"><span className="flex items-center gap-2"><LoaderCircle className="h-4 w-4 animate-spin text-indigo-600" />{text}</span></div>; }
export function Empty({ text, children }: { text: string; children?: ReactNode }) { return <div className="p-12 text-center text-sm text-slate-500"><Inbox className="mx-auto mb-3 h-8 w-8 text-slate-300" />{text}{children && <div className="mt-4">{children}</div>}</div>; }
export function ErrorState({ message, onRetry }: { message: string; onRetry?: () => void }) { return <div className="rounded-2xl border border-rose-100 bg-rose-50 p-6 text-sm text-rose-700"><div className="flex items-start gap-3"><CircleAlert className="mt-0.5 h-5 w-5 shrink-0" /><div className="flex-1"><p className="font-semibold">No pudimos cargar la información</p><p className="mt-1">{message}</p></div>{onRetry && <Button variant="secondary" onClick={onRetry}><RotateCw className="h-4 w-4" />Reintentar</Button>}</div></div>; }
export function Card({ children, className = '' }: { children: ReactNode; className?: string }) { return <div className={`overflow-hidden rounded-2xl border bg-white shadow-sm ${className}`}>{children}</div>; }
