import type { Moneda } from '../types';
const pad = (n: number) => String(n).padStart(2, '0');
const numberFormat = new Intl.NumberFormat('es-PE', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
export const round2 = (value: number): number => Math.round((value + Number.EPSILON) * 100) / 100;
export const currencySymbol = (moneda: Moneda = 'PEN'): string => (moneda === 'USD' ? 'US$' : 'S/');
export const formatCurrency = (value: number, moneda: Moneda = 'PEN'): string => `${value < 0 ? '-' : ''}${currencySymbol(moneda)} ${numberFormat.format(Math.abs(value ?? 0))}`;
export const parseDate = (value: string): Date => { const dateOnly = /^(\d{4})-(\d{2})-(\d{2})$/.exec(value); return dateOnly ? new Date(Number(dateOnly[1]), Number(dateOnly[2]) - 1, Number(dateOnly[3])) : new Date(value); };
export const formatDate = (value: string): string => new Intl.DateTimeFormat('es-PE', { day: '2-digit', month: 'short', year: 'numeric' }).format(parseDate(value));
export const formatDateTime = (value: string): string => new Intl.DateTimeFormat('es-PE', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit', second: '2-digit' }).format(parseDate(value));
export const dateKey = (value: string): string => value.slice(0, 10);
export const toDateInput = (date: Date = new Date()): string => `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
export const toDateTimeInput = (date: Date = new Date()): string => `${toDateInput(date)}T${pad(date.getHours())}:${pad(date.getMinutes())}`;
export const toApiDateTime = (value: string): string | undefined => { if (!value) return undefined; if (/^\d{4}-\d{2}-\d{2}$/.test(value)) return `${value}T00:00:00`; return /T\d{2}:\d{2}$/.test(value) ? `${value}:00` : value; };
export const toTimeSpan = (value: string): string | undefined => (!value ? undefined : /^\d{2}:\d{2}$/.test(value) ? `${value}:00` : value);
export const toPercent = (fraction: number): number => Math.round(fraction * 100 * 10000) / 10000;
export const fromPercent = (percent: number): number => Math.round((percent / 100) * 1e8) / 1e8;
export const formatPercent = (fraction: number): string => `${toPercent(fraction).toLocaleString('es-PE', { maximumFractionDigits: 4 })} %`;
export const formatWallClock = (value: string): string => { const m = /^(\d{4})-(\d{2})-(\d{2})(?:[T ](\d{2}):(\d{2})(?::(\d{2}))?)?/.exec(value); return m ? formatDateTime(new Date(Number(m[1]), Number(m[2]) - 1, Number(m[3]), Number(m[4] ?? 0), Number(m[5] ?? 0), Number(m[6] ?? 0)).toISOString()) : value; };
