export const HELP = {
  dni: 'Documento Nacional de Identidad: 8 dígitos.',
  ruc: 'Registro Único de Contribuyentes: 11 dígitos.',
  limiteCredito: 'Monto máximo de capital que el cliente puede deber a la vez. Cada compra descuenta de este límite.',
  creditoDisponible: 'Límite de crédito menos la deuda de capital pendiente.',
  moneda: 'Moneda en la que se otorga el crédito: soles (S/) o dólares (US$).',
  tipoTasa: 'TEA vs Nominal: la efectiva anual (TEA) ya incluye la capitalización; la nominal anual (TNA) no. El sistema convierte ambas a tasa mensual (TEM) con año comercial de 360 días.',
  tasaCompensatoria: 'Interés anual que paga el cliente por usar el crédito. Escríbela en %, por ejemplo 36 para 36 %.',
  tasaMoratoria: 'Interés anual por los días de atraso. Puede ser 0; en ese caso el motor usa la tasa compensatoria para calcular la mora.',
  diaCorte: 'Día del mes en que se cierra el ciclo y se agrupan las compras para el listado de pago. Debe ser un entero entre 1 y 28.',
  diaPago: 'Día del mes en que vence lo exigible del ciclo. Debe ser un entero entre 1 y 28; desde el día siguiente corre la mora.',
  maxMeses: 'Plazo máximo en meses que el cliente puede elegir al comprar en cuotas (1 a 36).',
  horaCorte: 'Hora del día de corte (hora de Lima) a partir de la cual el ciclo se considera cerrado. Opcional.',
  usuarioCliente: 'Usuario con el que el cliente entrará a ver su estado de cuenta.',
  password: 'Mínimo 6 caracteres.',
  passwordEdicion: 'Déjala vacía para conservar la contraseña actual.',
  modalidad: 'Fin de mes: se paga todo en la fecha de pago del ciclo. Cuotas: usa el método francés vencido; el capital se ajusta por la gracia hasta la fecha de pago de referencia y las cuotas vencen mensualmente después.',
  plazoMeses: 'Número de cuotas mensuales. No puede superar el plazo máximo del cliente.',
  fechaCompra: 'Opcional. Si la dejas vacía se usa la fecha y hora actual de Lima.',
  fechaPago: 'Opcional. Si la dejas vacía se usa la fecha actual de Lima. El monto exacto depende de esta fecha.',
  precioCredito: 'Precio al que se vende a crédito. Debe ser mayor que cero y no superar el crédito disponible.',
  precioLista: 'Precio a crédito del producto. Al comprar desde el catálogo se cobra precio lista × cantidad.',
  precioContado: 'Precio de referencia si el cliente pagara al contado.',
  cantidad: 'Unidades del producto. El total es precio lista × cantidad.',
  montoPago: 'Pago exacto: debe coincidir con el total exigible a la fecha de pago. No se aceptan pagos parciales ni excedentes.',
  imputacion: 'Imputación: el pago se aplica primero a la mora, luego al interés compensatorio y al final al capital.',
  totalExigible: 'Lo que el cliente debe pagar: capital vencido o del próximo pago, más intereses compensatorios y moratorios a la fecha.',
  fechaCorte: 'Fecha de cierre del ciclo de facturación.',
  interesCompensatorio: 'Interés por usar el crédito. Para fin de mes se calcula por días con TED; para cuotas se usa TEM dentro del método francés.',
  interesMoratorio: 'Interés por atraso, calculado por los días transcurridos desde el vencimiento.',
  listadoCorte: 'Resumen del ciclo: compras ordenadas, capital, días, interés compensatorio, cuotas exigibles y mora separada. Solo se guarda cuando el ciclo ya cerró.',
  unidadMedida: 'Unidad en que se vende el producto, por ejemplo: unidad, kg, caja.',
  modalidadesProducto: 'Modalidades de compra a crédito permitidas para este producto. Debe haber al menos una.',
  imagen: 'JPG, PNG o WEBP de hasta 2 MB.',
} as const;
